GET http://localhost:8080/packs/vasek
Accept: application/json

###
GET https://fx-server.herokuapp.com/packs
Accept: application/json

###
POST http://localhost:8080/packs
Content-Type: application/x-www-form-urlencoded

name=vasek

###

DELETE http://localhost:8080/packs
Content-Type: application/x-www-form-urlencoded

name=vasek

###

PUT http://localhost:8080/packs/vasek
Content-Type: application/x-www-form-urlencoded

###

