GET https://fx-server.herokuapp.com/packs
Accept: application/json

###
POST http://localhost:8080/packs
Content-Type: application/x-www-form-urlencoded

name=students

###

DELETE http://localhost:8080/packs
Content-Type: application/x-www-form-urlencoded

name=students

###